using BbQ.ChatWidgets.Abstractions;
using BbQ.ChatWidgets.Models;

namespace BbQ.ChatWidgets.Services;

/// <summary>
/// Default implementation of <see cref="IWidgetToolsProvider"/> that provides AI tools
/// for all available widget instances registered in the widget registry.
/// </summary>
/// <remarks>
/// This provider creates tools by wrapping each registered widget instance in a WidgetTool.
/// Tools are generated dynamically from the <see cref="IWidgetRegistry"/>, which means:
/// - All registered widgets (both built-in and custom) are automatically included
/// - New widgets registered at runtime are immediately available to the AI
/// - The registry is the single source of truth for available widget instances
/// - No metadata extraction needed — instances provide all required information
/// </remarks>
/// <remarks>
/// Initializes a new instance of the <see cref="DefaultWidgetToolsProvider"/> class.
/// </remarks>
/// <param name="registry">The widget registry to use for discovering available widgets.</param>
/// <exception cref="ArgumentNullException">Thrown if registry is null.</exception>
public sealed class DefaultWidgetToolsProvider(IWidgetRegistry registry) : IWidgetToolsProvider
{
    private readonly IWidgetRegistry _registry = registry ?? throw new ArgumentNullException(nameof(registry));
    private IReadOnlyList<WidgetTool>? _cachedTools;

    /// <summary>
    /// Gets the list of available widget tools for use by AI models.
    /// </summary>
    /// <returns>A read-only list of WidgetTool instances representing all registered widgets.</returns>
    /// <remarks>
    /// Tools are generated by wrapping each registered widget instance and cached
    /// after the first call for performance.
    /// </remarks>
    public IReadOnlyList<WidgetTool> GetTools()
    {
        if (_cachedTools != null)
            return _cachedTools;

        var tools = new List<WidgetTool>();

        // Create tools from all registered widget entries, passing the registry key as typeId
        tools.AddRange(_registry.GetInstances().Select(entry => new WidgetTool(entry)) ?? []);
        _cachedTools = tools.AsReadOnly();
        return _cachedTools;
    }
}
