using System.IO.Compression;
using System.Security.Cryptography;
namespace BbQ.LlamaCpp;
public sealed class VerifiedLlamaCppDependencyResolver(HttpClient client, LlamaCppDeploymentManifest manifest, LlamaCppDependencyOptions options) : ILlamaCppDependencyResolver
{
    public async ValueTask<LlamaCppDependencyReport> ResolveAsync(CancellationToken ct = default) { try { LlamaCppDeploymentManifestLoader.Validate(manifest); var runtime = Select(LlamaCppArtifactKind.Runtime, a => string.Equals(a.RuntimeIdentifier, options.RuntimeIdentifier, StringComparison.OrdinalIgnoreCase) && string.Equals(a.Backend, options.Backend, StringComparison.OrdinalIgnoreCase)); var model = Select(LlamaCppArtifactKind.GenerationModel, _ => true); var runtimePath = await InstallAsync(runtime, ct); var modelPath = await InstallAsync(model, ct); var executable = runtime.ArchiveKind == LlamaCppArchiveKind.None ? runtimePath : Path.Combine(runtimePath, runtime.ExecutableRelativePath ?? throw new InvalidDataException("Runtime executable path is required.")); if (!File.Exists(executable)) throw new FileNotFoundException("llama-server was not found.", executable); if (!OperatingSystem.IsWindows()) File.SetUnixFileMode(executable, File.GetUnixFileMode(executable) | UnixFileMode.UserExecute); return new(LlamaCppDependencyStatus.Ready, new(executable, modelPath, [runtime.ArtifactId, model.ArtifactId]), []); } catch (Exception ex) when (ex is not OperationCanceledException) { return new(LlamaCppDependencyStatus.Failed, null, [ex.Message]); } }
    private LlamaCppArtifact Select(LlamaCppArtifactKind kind, Func<LlamaCppArtifact, bool> predicate) { var values = manifest.Artifacts.Where(a => a.Kind == kind && predicate(a)).ToArray(); return values.Length == 1 ? values[0] : throw new InvalidDataException($"Manifest must select exactly one {kind} artifact."); }
    private async ValueTask<string> InstallAsync(LlamaCppArtifact artifact, CancellationToken ct) { var root = Path.GetFullPath(Path.Combine(options.RootDirectory, artifact.Kind.ToString(), artifact.ArtifactId)); Directory.CreateDirectory(root); var package = Path.Combine(root, artifact.FileName); if (File.Exists(package)) { await VerifyAsync(artifact, package, ct); return artifact.ArchiveKind == LlamaCppArchiveKind.None ? package : root; } var temp = package + ".tmp"; try { var offline = options.OfflineBundleDirectory is null ? null : Path.Combine(options.OfflineBundleDirectory, artifact.FileName); if (offline is not null && File.Exists(offline)) File.Copy(offline, temp, true); else if (artifact.Source.IsFile) File.Copy(artifact.Source.LocalPath, temp, true); else { if (!options.AllowNetworkDownloads) throw new InvalidOperationException($"Artifact '{artifact.ArtifactId}' is missing and downloads are disabled."); using var response = await client.GetAsync(artifact.Source, HttpCompletionOption.ResponseHeadersRead, ct); response.EnsureSuccessStatusCode(); await using var input = await response.Content.ReadAsStreamAsync(ct); await using var output = File.Create(temp); await input.CopyToAsync(output, ct); } await VerifyAsync(artifact, temp, ct); if (artifact.ArchiveKind == LlamaCppArchiveKind.None) File.Move(temp, package, true); else { if (artifact.ArchiveKind != LlamaCppArchiveKind.Zip) throw new NotSupportedException("TarGzip installation is not supported by this package version."); ZipFile.ExtractToDirectory(temp, root, true); File.Move(temp, package, true); } return artifact.ArchiveKind == LlamaCppArchiveKind.None ? package : root; } finally { if (File.Exists(temp)) File.Delete(temp); } }
    private static async ValueTask VerifyAsync(LlamaCppArtifact artifact, string path, CancellationToken ct) { if (new FileInfo(path).Length != artifact.SizeBytes) throw new InvalidDataException($"Artifact '{artifact.ArtifactId}' size verification failed."); await using var stream = File.OpenRead(path); var actual = Convert.ToHexString(await SHA256.HashDataAsync(stream, ct)); if (!actual.Equals(artifact.Sha256, StringComparison.OrdinalIgnoreCase)) throw new InvalidDataException($"Artifact '{artifact.ArtifactId}' SHA-256 verification failed."); }
}
