/**
 * Scenario configuration
 */

import { ScenarioType, ScenarioConfig } from '../models/chat.models';

export const SCENARIOS: ScenarioConfig[] = [
  {
    id: ScenarioType.BasicChat,
    name: 'Basic Chat',
    description: 'Traditional request-response chat. Send a message and receive the complete response.',
    endpoint: '/api/chat/message',
    features: [
      'Complete responses',
      'Widget support',
      'Thread context',
      'Simple implementation'
    ],
    icon: '💬'
  },
  {
    id: ScenarioType.StreamingChat,
    name: 'Streaming Chat',
    description: 'Real-time streaming responses. Watch content appear as it\'s generated by the AI.',
    endpoint: '/api/chat/stream/message',
    features: [
      'Real-time streaming',
      'Progressive content',
      'Lower latency perception',
      'Server-Sent Events'
    ],
    icon: '⚡'
  },
  {
    id: ScenarioType.TriageAgent,
    name: 'Triage Agent',
    description: 'Intelligent routing. Your message is classified and routed to the appropriate agent.',
    endpoint: '/api/chat/agent',
    features: [
      'Intent classification',
      'Specialized agents',
      'Smart routing',
      'Agent-to-agent communication'
    ],
    icon: '🎯'
  },
  {
    id: ScenarioType.WidgetsDemo,
    name: 'Widgets Demo',
    description: 'Explore all available widgets. Buttons, forms, dropdowns, sliders, and more.',
    endpoint: '/api/chat/message',
    features: [
      '13+ widget types',
      'Interactive UI',
      'Rich content',
      'Form handling'
    ],
    icon: '🧩'
  },
  {
    id: ScenarioType.ActionsDemo,
    name: 'Actions Demo',
    description: 'Widget interactions. Click buttons, fill forms, and trigger actions.',
    endpoint: '/api/chat/action',
    features: [
      'Widget actions',
      'Typed payloads',
      'Action handlers',
      'Context preservation'
    ],
    icon: '🎬'
  },
  // Temporarily disabled due to NG0203 injection context error
  // TODO: Fix the injection context issue with custom widget renderers
  // The error occurs when the base WidgetRendererComponent from the library is used in a template.
  // Despite using constructor parameter injection (not inject()), Angular throws NG0203 error.
  // This may be related to how ng-packagr bundles the component or Angular 19's DI system.
  // Possible solutions to investigate:
  // 1. Check if there's a circular dependency causing the issue
  // 2. Try making WidgetRendererComponent a directive instead of a component
  // 3. Use providedIn: 'any' for WidgetRegistryService
  // 4. Create a factory provider for the base component
  /*
  {
    id: ScenarioType.CustomWidgetDemo,
    name: 'Custom Widget Renderers',
    description: 'Demonstrates three approaches for custom widget rendering with Angular.',
    endpoint: 'N/A',
    features: [
      'HTML function renderer',
      'Angular component renderer',
      'Template renderer',
      'Full Angular features'
    ],
    icon: '🎨'
  },
  */
  {
    id: ScenarioType.SseWidgets,
    name: 'SSE Widget Updates',
    description: 'Demonstrates server-sent events updating widgets in real-time.',
    endpoint: '/api/chat/widgets/streams/{streamId}/events',
    features: [
      'Server-Sent Events',
      'Targeted widget updates',
      'DOM replacement',
      'Live demo'
    ],
    icon: '📡'
  },
  {
    id: ScenarioType.SseClock,
    name: 'SSE Clock',
    description: 'A live clock powered by server-sent events (SSE).',
    endpoint: '/api/chat/widgets/streams/{streamId}/events',
    features: [
      'Server-Sent Events',
      'Periodic updates',
      'Minimal example',
      'Auto-refresh'
    ],
    icon: '⏰'
  }
];

export function getScenario(id: ScenarioType): ScenarioConfig | undefined {
  return SCENARIOS.find(s => s.id === id);
}
