/**
 * Scenario configuration
 */

import { ScenarioType, ScenarioConfig } from '../types';

export const SCENARIOS: ScenarioConfig[] = [
  {
    id: ScenarioType.BasicChat,
    name: 'Basic Chat',
    description: 'Traditional request-response chat. Send a message and receive the complete response.',
    endpoint: '/api/chat/message',
    features: [
      'Complete responses',
      'Widget support',
      'Thread context',
      'Simple implementation'
    ],
    icon: '💬'
  },
  {
    id: ScenarioType.StreamingChat,
    name: 'Streaming Chat',
    description: 'Real-time streaming responses. Watch content appear as it\'s generated by the AI.',
    endpoint: '/api/chat/stream/message',
    features: [
      'Real-time streaming',
      'Progressive content',
      'Lower latency perception',
      'Server-Sent Events'
    ],
    icon: '⚡'
  },
  {
    id: ScenarioType.TriageAgent,
    name: 'Triage Agent',
    description: 'Intelligent routing. Your message is classified and routed to the appropriate agent.',
    endpoint: '/api/chat/agent',
    features: [
      'Intent classification',
      'Specialized agents',
      'Smart routing',
      'Agent-to-agent communication'
    ],
    icon: '🎯'
  },
  {
    id: ScenarioType.WidgetsDemo,
    name: 'Widgets Demo',
    description: 'Explore all available widgets. Buttons, forms, dropdowns, sliders, and more.',
    endpoint: '/api/chat/message',
    features: [
      '13+ widget types',
      'Interactive UI',
      'Rich content',
      'Form handling'
    ],
    icon: '🧩'
  },
  {
    id: ScenarioType.ActionsDemo,
    name: 'Actions Demo',
    description: 'Widget interactions. Click buttons, fill forms, and trigger actions.',
    endpoint: '/api/chat/action',
    features: [
      'Widget actions',
      'Typed payloads',
      'Action handlers',
      'Context preservation'
    ],
    icon: '🎬'
  }
  ,{
    id: ScenarioType.SseWidgets,
    name: 'SSE Widget Updates',
    description: 'Demonstrates server-sent events updating widgets in real-time.',
    endpoint: '/api/chat/widgets/streams/{streamId}/events',
    features: [
      'Server-Sent Events',
      'Targeted widget updates',
      'DOM replacement',
      'Live demo'
    ],
    icon: '📡'
  }
  ,{
    id: ScenarioType.SseClock,
    name: 'SSE Clock',
    description: 'A live clock powered by server-sent events (SSE).',
    endpoint: '/api/chat/widgets/streams/{streamId}/events',
    features: [
      'Server-Sent Events',
      'Periodic updates',
      'Minimal example',
      'Auto-refresh'
    ],
    icon: '⏰'
  }
];

export function getScenario(id: ScenarioType): ScenarioConfig | undefined {
  return SCENARIOS.find(s => s.id === id);
}
